### ISSUE TITLE
Wrong Consul user home creation

### ISSUE THREAD

**Issue by jnogol** [idealista/consul-role#13]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

Consul user home is created, but set to `/bin/false`, which is an incongruent behaviour. Anyway, the task doesn't fail until a group change is attemped.

A more sensible configuration would be:

``` yaml
- name: Consul | Ensure consul user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    createhome: no
```

### Steps to Reproduce

1. Provision a machine with the role and `consul_group: foo`
2. Change `consul_group: bar`
3. Grab a cup of coffee and watch the playbook fail.

**Expected behavior:** User group changed

**Actual behavior:** Error `usermod: Failed to change ownership of the home directory`

**Reproduces how often:** Like Snape said: "always"

### Versions

All
