### ISSUE TITLE
Script checks can't be used

### ISSUE THREAD

**Issue by jnogol** [idealista/consul-role#22]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

When trying to register a service and use `script_check`, the following error comes up:
```
scripts are disabled on this agent to enable configure 'enable script checks' to true
```
and Consul won't start up.
### Steps to Reproduce

1. Set this in a variables file:

``` yml
consul_services_register:
  - name: my-service
    port: 8080
    script: "./opt/script/check_status.sh"
    interval: 30s
```
2. Run the playbook

**Expected behavior:** 

Playbook run succesfully and service is registered

**Actual behavior:**

Service is not registered

**Reproduces how often:** Always

### Versions

1.2.1 and earlier
